<a href="https://colab.research.google.com/github/kk-2006-hub/Hands-on-experience/blob/main/29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import*

In [ ]:
data=pd.read_csv('/content/breast_cancer _ day1.csv')


In [ ]:
data

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
data.head()

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [ ]:
data=data.drop('id',axis=1)

In [ ]:
data.shape

(569, 31)

In [ ]:
x=data.drop('diagnosis',axis=1)

In [ ]:
x.shape

(569, 30)

In [ ]:
y=data['diagnosis']

In [ ]:
y.shape

(569,)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y=pd.DataFrame(y)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
x

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [ ]:
x=pd.DataFrame(x)

In [ ]:
x.head()

0         1         2   ...        27        28        29
0  1.097064 -2.073335  1.269934  ...  2.296076  2.750622  1.937015
1  1.829821 -0.353632  1.685955  ...  1.087084 -0.243890  0.281190
2  1.579888  0.456187  1.566503  ...  1.955000  1.152255  0.201391
3 -0.768909  0.253732 -0.592687  ...  2.175786  6.046041  4.935010
4  1.750297 -1.151816  1.776573  ...  0.729259 -0.868353 -0.397100

[5 rows x 30 columns]

In [ ]:
x.shape

(569, 30)

In [ ]:
y.shape

(569, 1)

In [ ]:
from sklearn.model_selection import (train_test_split)
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=3)

In [ ]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(455, 30)
(114, 30)
(455, 1)
(114, 1)


In [ ]:
y.value_counts()

0
0    357
1    212
Name: count, dtype: int64

In [ ]:
ytrain.value_counts()

0
0    283
1    172
Name: count, dtype: int64

In [ ]:
model=Sequential()

In [ ]:
model.add(Dense(16,input_dim=30,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(xtrain,ytrain,epochs=50,validation_data=(xtest,ytest))

Epoch 1/50


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8055 - loss: 0.5248 - val_accuracy: 0.8860 - val_loss: 0.4086
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8931 - loss: 0.3907 - val_accuracy: 0.9298 - val_loss: 0.2968
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9175 - loss: 0.2947 - val_accuracy: 0.9298 - val_loss: 0.2216
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9387 - loss: 0.2174 - val_accuracy: 0.9386 - val_loss: 0.1759
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9426 - loss: 0.1866 - val_accuracy: 0.9386 - val_loss: 0.1505
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9598 - loss: 0.1402 - val_accuracy: 0.9561 - val_loss: 0.1336
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9672 - loss: 0.1209 - val_accuracy: 0.9474 - val_loss: 0.1227
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9658 - loss: 0.1235 - val_accuracy: 0.9386 - val_loss: 0.1153
Ep

In [ ]:
ypred=model.predict(xtest)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


In [ ]:
ypred
ypred=ypred.round()

In [ ]:
ypred

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
ac=accuracy_score(ytest,ypred)
ac

0.956140350877193

In [ ]:
cm=confusion_matrix(ytest,ypred)
cm

array([[72,  2],
       [ 3, 37]])